channels:
- conda-forge
# - cxwang #required for MSPASS?
- mspass

dependencies:
- nodejs
- python==3.11.*
- nbgitpuller=1.1.*

- jupyterlab
- jupyterhub-singleuser>3.0,<4.0
- jupyter-server-proxy

- ipympl
- pytest
- mspasspy
- pyarrow>14.0.1
- pip
- pip:
  # - pymongo  #already included in mspass installation
  - dask-labextension
  - earthscope-sdk

variables:
  MSPASS_HOME: './srv/mpsass/'
