version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      # Generate the Sphinx configuration for this Jupyter Book so it builds.
      - "jupyter-book config sphinx docs/"

python:
   install:
   - requirements: docs/requirements.txt

#sphinx:
#  builder: html
#  fail_on_warning: true

#https://github.com/readthedocs-examples/example-jupyter-book/blob/main/.readthedocs.yaml