# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: GeoLab Jupyter Book
author: EarthScope On-Ramp Project Group
logo: content/img/cloud_logo_simple_small.png
copyright: "2024" # Should go in the footer

parse:
  myst_substitutions:
    geolab_github_url: https://github.com/EarthScope/GeoLab
    jupyterhub_url: https://geolab.earthscope.cloud/hub/
    website_url: https://www.earthscope.org/data/geolab/
    geolab_feedback_form: https://support.center.earthscope.org/servicedesk/customer/portal/4/group/31/create/210


# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  # execute_notebooks: force
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
#  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  url: https://github.com/EarthScope/GeoLab
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: true

# Specify what to build
only_build_toc_files: true
exclude_patterns: [
  content/drafts/*,
  content/science_tutorials/*
]