#!/bin/bash
# /srv/start — entrypoint for geolab-slim
# Pangeo's ENTRYPOINT is /srv/start. We just exec whatever was passed
# as CMD (defaulted to jupyter lab; JupyterHub spawning overrides with
# jupyterhub-singleuser).
exec "$@"
